In [1]:
import pandas as pd
from pathlib import Path

clinical_path = Path("../data/raw/gbm_tcga_pan_can_atlas_2018_clinical.tsv")

clinical = pd.read_csv(clinical_path, sep="\t")

print("Rows:", clinical.shape[0])
print("Columns:", clinical.shape[1])

Rows: 592
Columns: 63

In [2]:
clinical[["Patient ID", "Sample ID", "Sample Type"]].head(10)

     Patient ID        Sample ID Sample Type
0  TCGA-02-0001  TCGA-02-0001-01     Primary
1  TCGA-02-0003  TCGA-02-0003-01     Primary
2  TCGA-02-0006  TCGA-02-0006-01     Primary
3  TCGA-02-0007  TCGA-02-0007-01     Primary
4  TCGA-02-0009  TCGA-02-0009-01     Primary
5  TCGA-02-0010  TCGA-02-0010-01     Primary
6  TCGA-02-0011  TCGA-02-0011-01     Primary
7  TCGA-02-0014  TCGA-02-0014-01     Primary
8  TCGA-02-0015  TCGA-02-0015-01     Primary
9  TCGA-02-0016  TCGA-02-0016-01     Primary

In [ ]:
samples_per_patient = clinical.groupby("Patient ID")["Sample ID"].nunique()

samples_per_patient.value_counts().sort_index()

# 578 patients have 1 sample only, 7 patients have 2 samples

Sample ID
1    578
2      7
Name: count, dtype: int64

In [ ]:
clinical[clinical["Patient ID"].isin(
    samples_per_patient[samples_per_patient > 1].index
)][["Patient ID", "Sample ID", "Sample Type"]].sort_values("Patient ID")

# Actual 7 patients with multiple (2) samples == 14 records."

       Patient ID        Sample ID Sample Type
95   TCGA-06-0125  TCGA-06-0125-01     Primary
96   TCGA-06-0125  TCGA-06-0125-02  Recurrence
132  TCGA-06-0171  TCGA-06-0171-01     Primary
133  TCGA-06-0171  TCGA-06-0171-02  Recurrence
147  TCGA-06-0190  TCGA-06-0190-01     Primary
148  TCGA-06-0190  TCGA-06-0190-02  Recurrence
156  TCGA-06-0210  TCGA-06-0210-01     Primary
157  TCGA-06-0210  TCGA-06-0210-02  Recurrence
158  TCGA-06-0211  TCGA-06-0211-01     Primary
159  TCGA-06-0211  TCGA-06-0211-02  Recurrence
164  TCGA-06-0221  TCGA-06-0221-01     Primary
165  TCGA-06-0221  TCGA-06-0221-02  Recurrence
363  TCGA-14-1034  TCGA-14-1034-01     Primary
364  TCGA-14-1034  TCGA-14-1034-02  Recurrence

In [5]:
clinical["Sample Type"].value_counts(dropna=False)

Sample Type
Primary       585
Recurrence      7
Name: count, dtype: int64

In [ ]:
primary_clinical = clinical[
    clinical["Sample Type"] == "Primary"
].copy()

print("Primary samples:", primary_clinical["Sample ID"].nunique())
print("Primary patients:", primary_clinical["Patient ID"].nunique())
print("Rows:", primary_clinical.shape[0])

# primary_clinical stores only primary samples i.e. 578 samples from 578 patients, no duplicates

Primary samples: 585
Primary patients: 585
Rows: 585

In [7]:
primary_clinical["Patient ID"].duplicated().sum()

np.int64(0)

In [ ]:
from pathlib import Path

processed_path = Path("../data/processed/gbm_primary_clinical.tsv")

primary_clinical.to_csv(
    processed_path,
    sep="\t",
    index=False
)

print("Saved to:", processed_path)
print("Exists:", processed_path.exists())

# Save the processed file to the data/processed directory for future use.

Saved to: ..\data\processed\gbm_primary_clinical.tsv
Exists: True